customhost = "database-1.cticlgog7jgy.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tanyongyue-employee"
customregion = "us-east-1"